version: "3"

services:
  database:
    image: mysql:5.7
    container_name: mysqlContainer
    restart: always
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    volumes:
      - db-data:/etc/mysql/config
    ports:
      - "30678:3306"
    expose:
      - "30678"
    # networks:
    #   - server_network

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php_myadminContainer
    ports:
      - "8200:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_ROOT_PASSWORD=root
    restart: always
    depends_on:
      - database
    # networks:
    #   - server_network

  # app:
  #   build:
  #     context: ./
  #     dockerfile: dev.dockerfile
  #   image: backend
  #   container_name: Web_backend
  #   restart: always
  #   environment:
  #     - MYSQL_HOST=mysql
  #     - MYSQL_PORT=30678
  #   volumes:
  #     - ./src:/app/src
  #   ports:
  #     - 5278:5278
  #   depends_on:
  #     - mysql
  #   expose:
  #     - 5278
  #   networks:
  #     - server_network
volumes:
  db-data:
    driver: local
# networks:
#   server_network:
#     external:
#       name: my_network
