 
version: "3"

services:
  
  database:
    image: postgres:11.1
    container_name: pgContainer
    restart: always
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "30678:5432"
    expose:
      - "30678"

volumes:
  db-data:
    driver: local